shared:
  support: jobs@quebecdevs.com
  support_mailbox: "Quebec Devs Talent <admin@codeboxx.biz>"
  notifications_mailbox: "Quebec Devs Talent <admin@codeboxx.biz>"
  updates_mailbox: "Quebec Devs Talent <admin@codeboxx.biz>"
  reminders_mailbox: "Quebec Devs Talent <admin@codeboxx.biz>"
