shared:
  support: jobs@quebecdevs.com
  support_mailbox: "Quebec Devs Talent <jobs@quebecdevs.com>"
  notifications_mailbox: "Quebec Devs Talent <jobs@quebecdevs.com>"
  updates_mailbox: "Quebec Devs Talent <jobs@quebecdevs.com>"
  reminders_mailbox: "Quebec Devs Talent <jobs@quebecdevs.com>"
