shared:
  support: jobs@quebecdevs.com
  support_mailbox: "Quebec Devs Talent <info@quebec.dev>"
  notifications_mailbox: "Quebec Devs Talent <info@quebec.dev>"
  updates_mailbox: "Quebec Devs Talent <info@quebec.dev>"
  reminders_mailbox: "Quebec Devs Talent <info@quebec.dev>"
